name: foodrena_mobile
description: Foodrena customer & rider mobile app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI / Core
  cupertino_icons: ^1.0.6
  provider: ^6.1.2

  # Networking
  http: ^1.2.1
  socket_io_client: ^2.0.3+1

  # Storage
  shared_preferences: ^2.2.2

  # Utils
  intl: ^0.19.0

  # WebView (Paystack)
  webview_flutter: ^4.7.0

  # Maps
  google_maps_flutter: ^2.6.1

  # Location (rider tracking)
  geolocator: ^11.0.0
  permission_handler: ^11.3.0

  # Image
  image_picker: ^1.1.0

  # Links (support screen — WhatsApp, phone, email)
  url_launcher: ^6.3.0

  # In-app calls (Agora)
  agora_rtc_engine: ^6.3.2

   # Rider order alert
  vibration: ^2.0.0

  # Firebase / Notifications
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^17.0.0
  firebase_auth: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/splash_frames/

flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/foodrena_logo3.png"