name: foodrena_mobile
description: Foodrena customer & rider mobile app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI / Core
  cupertino_icons: ^1.0.6
  provider: ^6.1.2

  # Networking
  http: ^1.2.1
  socket_io_client: ^2.0.3+1

  # Storage
  shared_preferences: ^2.2.2

  # Utils
  intl: ^0.19.0

  # WebView (Paystack)
  webview_flutter: ^4.7.0

  # Maps
  google_maps_flutter: ^2.6.1

  # Location (rider tracking)
  geolocator: ^11.0.0
  permission_handler: ^11.3.0

  # Image
  image_picker: ^1.1.0

  # Firebase / Notifications ✅
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/